baseURL = "https://metaiot.group/" # 请替换为你的实际域名
# languageCode = "en-us" # 移除单独的 languageCode，移入下方 languages 块
title = "MetaIoT"
theme = [] 

defaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1
    title = "MetaIoT"
    [languages.en.params]
      subtitle = "Welcome to MetaIoT Lab."
      description = "We create the next generation of intelligent wireless systems for communication and sensing with applications in autonomous systems, mixed reality, and IoT."

  [languages.zh]
    languageName = "中文"
    languageCode = "zh-cn"
    weight = 2
    title = "MetaIoT"
    [languages.zh.params]
      subtitle = "欢迎来到 MetaIoT 实验室"
      description = "我们致力于研发下一代智能无线通信与感知系统，应用于自主系统、混合现实和物联网等领域。"

# 启用内联 HTML 
[markup.goldmark.renderer]
unsafe = true


[markup.highlight]
style = "monokai" # Rouge 的替代品，风格可选
lineNos = false

# 全局参数
[params]
subtitle = "Welcome to MetaIoT Lab."
description = "We create the next generation of intelligent wireless systems for communication and sensing with applications in autonomous systems, mixed reality, and IoT."
header_image = "images/background.webp"
footer_image = "images/background.webp"
google_scholar = "YkD8hs0AAAAJ"
[params.links]
    email = "mailto:wangw@whu.edu.cn" 
    google-scholar = "https://scholar.google.com/citations?user=YkD8hs0AAAAJ"
    github = "https://github.com/MetaIoT-WHU"
    youtube = "https://www.youtube.com/channel/WeiWANGWilliam"


[menu]
